travis:
  secure:
    BINSTAR_TOKEN: IaajVUy4f6SDu57mENyuxMsyGhZh5vU1+4bprROFUhkV0gzgSzQIvDI+5u5BdmnhKzQ/MpiYYxBVTrOVLPe1S6d0/y8ze6TtoCj/RPaZ6ePvPrq8iZFo5NYBzbadTmHnsrGMuxrbyRCavVbHl3NG/IkC2Yfh1Me3n1BnM4JO7JfW1TZircPUWbRrHQ2KCvz/Bj1Q9+/QLU+TD0UUmJp3uBjENvx4iyx9HsKGaciFfV3eRbyMKlyRI2w2UhxTWptnAbycBqkR/PLjeCmI51yGy7UApRuIG7l7Bd9UpW6CEVXiCWxRj7kE+YNVpVduQLBDVm1pNLgEUDCIMNVXZ7ErtW/9gGrw0YN6tNdhMe9bqJZBRrhFlWDYVDWefxy5ZD6mFGUmVL0lsVzMN85uDwhaThDI4KQmijg/YsErVpOqK0S4F2ycPwDwOhyay+mDULNe4fcyWZt2tExdiE+m2TzzK2aCQvvKtPLSG+7yjM8FQ4aivzYpcavBdV0eA0o6+JL1Au+b6TwdBoH9V2vExfek9xeXncXQmgsruixBmcBDGFn8LMBL0kOcCcg2QPmEHayPfFLBhdnODx8QVoAJUONufCZrcuqV6RJMiDdKqFNU7N4e0KbzxHLEQIoxPbkFuvxpwKuCoqLdNbVhOtx8nr/xhXIf+6q09M3Iz2UMx90ZBko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
